"""empty message

Revision ID: b551ba6a7aa2
Revises: 
Create Date: 2025-06-16 21:59:41.147730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b551ba6a7aa2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('policyholders', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_policyholders_id'), table_name='policyholders')
    op.drop_column('policyholders', 'id')
    op.create_table('autoupload_emails',
    sa.Column('id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('alias', sa.VARCHAR(length=255), nullable=False),
    sa.Column('domain', sa.VARCHAR(length=255), nullable=False),
    sa.Column('policy_holder_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['policy_holder_id'], ['policyholders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias', 'policy_holder_id', name='unique_alias_policyholder_pair')
    )
    op.create_index(op.f('ix_autoupload_emails_alias'), 'autoupload_emails', ['alias'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policyholders', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_policyholders_id'), 'policyholders', ['id'], unique=True)
    op.alter_column('policyholders', 'id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_autoupload_emails_alias'), table_name='autoupload_emails')
    op.drop_table('autoupload_emails')
    # ### end Alembic commands ###
